ALTER TYPE "AppointmentStatus" ADD VALUE IF NOT EXISTS 'CHECKED_IN';
ALTER TYPE "AppointmentStatus" ADD VALUE IF NOT EXISTS 'IN_ROOM';

ALTER TABLE "appointments"
ADD COLUMN IF NOT EXISTS "checked_in_at" TIMESTAMP(3),
ADD COLUMN IF NOT EXISTS "entered_room_at" TIMESTAMP(3);
